import "./globals.css";

import type { Metadata } from "next";
import { Roboto_Flex, Roboto_Mono } from "next/font/google";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  variable: "--font-roboto-flex",
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${robotoFlex.variable} ${robotoMono.variable} antialiased`}
      lang="en"
    >
      <body>{children}</body>
    </html>
  );
}
